### ISSUE TITLE
Support for GIFs (and other images)

### ISSUE THREAD

**Issue by victorb** [olahol/reactpack#12]
Today, you have the following part in the webpack configuration

``` javascript
  loaders.push({
    test: /\.(png)$/,
    loader: 'url?limit=100000'
  })
```

https://github.com/olahol/reactpack/blob/cc5692ee2332c10e6c14138227c214c7e6320539/config.js#L106-L109

Can we do something about other images as well, probably with a different loader? My guess is that the url-loader actually writes the image to base64 and puts it directly in the url, which wouldn't work for bigger images like GIFs or simply HQ ones.

**Comment by victorb** [comment]
Workaround in the meantime is to use the loader syntax when requireing things...

Example:

``` javascript
var happy_beardy = require('file?name=[hash]!./assets/laugh.gif')
// happy_beardy = hash with path to image in /dist
```

**Comment by olahol** [comment]
I've added `gif` to `url-loader` now, thank you @VictorBjelkholm.

**Comment by victorb** [comment]
Much better, thanks @olahol 👍
