### ISSUE TITLE
Add option to not inject bundle script

### ISSUE THREAD

**Issue by stursby** [olahol/reactpack#18]
So I ran into an issue using `reactpack` with `react-router` where `bundle.js` couldn't be loaded on nested routes because it was injected as a relative path. Setting `inject: false` in [config.js](https://github.com/olahol/reactpack/blob/master/config.js#L186) and manually including `bundle.js` in my `index.ejs` template allows it to work on all routes. For example:

Here's my updated `config.js`:

``` js
config.plugins.push(new HtmlWebpackPlugin({
      title: 'Reactpack App',
      dev: options.dev,
      port: options.port,
      template: template,
      inject: false    
}))
```

And my `index.ejs`:

```
<script src="/bundle.js"></script>
```

So maybe adding an option/flag like `--no-inject` ?

Let me know your thoughts.

**Comment by erikhuisman** [comment]
Or add `output.publicPath = '/'` to the webpack config

**Comment by olahol** [comment]
In version `0.6.0` I have added the options `--no-inject` and `--absolute-path` to the cli, which should work for your case. Also the dev server now uses absolute paths by default. Thank you both @erikhuisman and @stursby.
