### ISSUE TITLE
Custom additional babelrc?

### ISSUE THREAD

**Issue by meghprkh** [olahol/reactpack#19]
Hello can you support a custom babelrc? This babelrc should only add to the default presets. This is useful in cases when we need to add an additional babel plugin (like decorators) or we need to use preact instead of react and thus want to use `h` instead of `React.createElement`

**Comment by olahol** [comment]
This has now been added in version `0.6.0`, it will look for a local `.babelrc` and merge that with reactpacks babel settings. Thank you @meghprkh.

**Comment by meghprkh** [comment]
Thanks and keep up the awesome work!
