### ISSUE TITLE
Additional webpack settings

### ISSUE THREAD

**Issue by saidimu** [olahol/reactpack#20]
Is there a way to add custom settings to the default webpack confg? Something along the lines of what was just added for `babelrc` #19 ?

I'm looking for a way to add/override webpack loaders.

**Comment by olahol** [comment]
Not right now, but I will look into adding a search for `webpack.config.js` and if found merging it with `reactpack`'s config.

**Comment by olahol** [comment]
Thank you @saidimu, in version `0.7.0` you can now add a custom `webpack.config.js` that will merge into reactpacks config.

https://github.com/olahol/reactpack#how-do-i-add-other-loaders
