### ISSUE TITLE
Version 0.7.4 not available and version 0.7.5 not documented

### ISSUE THREAD

**Issue by victorb** [olahol/reactpack#28]
Seems that the last `npm publish` published version 0.7.5 rather than 0.7.4.

0.7.4 is nowhere to be found (Run `npm info reactpack .versions` to see all versions) and version 0.7.5 is not mentioned in the readme.

I'm assuming that this was a mistake and simply 0.7.4 was published as 0.7.5?

**Comment by olahol** [comment]
Yeah, I made a mistake version `0.7.4` was published as version `0.7.5` :disappointed:, I think I am going to leave it and just update the `CHANGELOG.md`.

**Comment by victorb** [comment]
Sounds good enough to me :)

Great work otherwise with reactpack!

Sincerely,
Victor Bjelkholm
(+34) 672 15 90 89
