### ISSUE TITLE
react-hot-loader incompatible with react 15.4.1

### ISSUE THREAD

**Issue by erikhuisman** [olahol/reactpack#30]
In watch mode react pack throws `Module not found: Error: Cannot resolve module 'react/lib/ReactMount'` to fix this you can add an alias to webpack config like so:

```
    resolve: {
        alias: { 'react/lib/ReactMount': 'react-dom/lib/ReactMount' }
    }
```

**Comment by olahol** [comment]
Thanks, changes in version `0.9.0`.
