### ISSUE TITLE
What is the cross platform compatibility?

### ISSUE THREAD

**Issue by Pomax** [olahol/reactpack#4]
I know autoless had issues on windows, so just to be sure: can the README.md be updated with information on known OS compatibility/incompatibility? Most of the things mentioned suggest it should work on any OS, but has that been verified?

**Comment by olahol** [comment]
I only own a Linux computer, there might be some problems on Windows, I don't know, I will have to get back to you on that.

**Comment by codehz** [comment]
I only find a bug in windows #7 @olahol

**Comment by Pomax** [comment]
@olahol nice way around that particular problem: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ has all the windows VMs you could possibly need to verify npm installs/tests pass for windows machines, even if you don't own one yourself =)

(they come with a 1 month expiry, but for node script testing purposes that's usually entirely irrelevant)

**Comment by olahol** [comment]
Thanks @Pomax , I'm installing one right now :+1:

**Comment by olahol** [comment]
I've tested it on Windows 7 now with node 6 and npm 3, and everything is working as expected.

**Comment by jarrydfillmore** [comment]
Had the same issue but resolved. Thank you!

**Comment by Pomax** [comment]
@olahol awesome. Worth putting in the README as a "tested and works on..." section? (always useful in case people go "omg what about windows 95 with Node 0.10?!?!1")

**Comment by olahol** [comment]
Ok, I've added the platforms I've tested on in the readme now :)

**Comment by Pomax** [comment]
hero++
