### ISSUE TITLE
Consider allowing a command-line switch to use an alternate linter

### ISSUE THREAD

**Issue by alanhogan** [olahol/reactpack#6]
Of course I can add my own to a project, but I do like the simple CLI you’ve exposed here…

In short: the so-called `standard` linter is not to everyone’s liking. No semicolons, in particular, ruffles my feathers. 

Thoughts?

**Comment by olahol** [comment]
I think it's a good idea, are you ok with [`semistandard`](https://github.com/Flet/semistandard)?

**Comment by gpmcadamold** [comment]
What if you already have a `.(es|js)lintrc` file, it ignores the built in standards and uses that?

**Comment by naholyr** [comment]
I think @gpmcadam nailed it: no specific CLI option may be needed, just by exploring dot files you can know what linter is used ;) if you really have to choose, eslint and jslint are way more populare than semistandard (or even standard, if I should guess).

**Comment by alanhogan** [comment]
Using dotfiles would be great.

**Comment by naholyr** [comment]
I get a cons: linters can be enabled and configured in many ways, for example for eslint you will want to check for 6 possibilities : .eslintrc[.js,.json,.yml,.yaml] or eslintConfig key in package.json.
Complexity might get out of control.

**Comment by olahol** [comment]
I've added lookup of various eslint configs for linting in version `0.3.0`. Give me some feedback if you guys think it's working as expected.
