### ISSUE TITLE
 Incorrect progress bar is displayed in win10

### ISSUE THREAD

**Issue by codehz** [olahol/reactpack#7]
![image](https://cloud.githubusercontent.com/assets/13158903/15782833/4fa2ee48-29de-11e6-8fd2-e8521d685b30.png)
A option should be add to disable this mode...or fix this bug.

**Comment by olahol** [comment]
Thank you for reporting this, I will fix this today after work :+1:

**Comment by olahol** [comment]
I've fixed this in version `0.3.1`, there was problem with the calculation of columns on the windows terminal.
